/*Author: Gustavo Nogueira
 *Date: 28/12/2017
 */

/*This function is responsible for generating each ILBP code.
 *It receives an array containing the central pixel and the other pixels to form the neighborhood of eight.
 *Returns the lowest ILBP code generated by combining binaries generated by the ILBP algorithm. */

void Get_Neighborhood_ILBP_GLCM(int **mat_IMG, int lines, int columns,double **feature_Vectors,int sizeVector,int vet_Index,int gray_Levels){
    double avg,sum = 0;
    int ln,cl;
    int px_Ref;
    int x,y,z,w,i,j;
    int mat_neighbors[3][3];
    int mat_bin[3][3];
    int vet_bin[9];
    int codILBP;
    double metrics_GLCM[24];

    //Matriz de Co-Ocorrência(MCO).
    int **MCO_Degree_0;
    int **MCO_Degree_45;
    int **MCO_Degree_90;
    int **MCO_Degree_135;
    int **MCO_Degree_180;
    int **MCO_Degree_225;
    int **MCO_Degree_270;
    int **MCO_Degree_315;

    //Alocação das MCOs
    MCO_Degree_0 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_45 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_90 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_135 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_180 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_225 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_270 = (int **) calloc(gray_Levels,sizeof(int *));
    MCO_Degree_315 = (int **) calloc(gray_Levels,sizeof(int *));

    for (w = 0;w < gray_Levels;w++){
        MCO_Degree_0[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_45[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_90[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_135[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_180[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_225[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_270[w] = (int *) calloc(gray_Levels,sizeof(int));
        MCO_Degree_315[w] = (int *) calloc(gray_Levels,sizeof(int));
    }

    //Busca a próxima vizinhaça de 8.
    for (w = 1;w < lines-1;w++){
        for (x = 1;x < columns-1;x++){
            for (y = 0;y < 3;y++){
                for (z = 0;z < 3;z++){
                    if (y == 0) ln = w - 1;
                        else if (y == 1) ln = w ;
                            else if (y == 2) ln = w + 1;
                    if (z == 0) cl = x - 1;
                        else if (z == 1) cl = x ;
                            else if (z == 2) cl = x + 1;
                    mat_neighbors[y][z] = mat_IMG[ln][cl];
                }
            }

            //Formando as GLCMs
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_0,0);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_45,45);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_90,90);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_135,135);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_180,180);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_225,225);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_270,270);
            Generate_GLCM(&mat_neighbors[0][0],MCO_Degree_315,315);

            //Calcula o código ILBP
            codILBP = Calculate_ILBP(&mat_neighbors[0][0]);

            feature_Vectors[vet_Index][codILBP] = feature_Vectors[vet_Index][codILBP] + 1;//Aumenta a frequência do código.

        }
    }

    //Gerando as métricas
    Generate_Metrics_GLCM(metrics_GLCM,MCO_Degree_0,MCO_Degree_45,MCO_Degree_90,MCO_Degree_135,MCO_Degree_180,MCO_Degree_225,MCO_Degree_270,MCO_Degree_315);

    //Concateando Vetores, formando o vetor características.
    j = 0;
    for (i = (2*gray_Levels);i < sizeVector;i++){
        feature_Vectors[vet_Index][i] = metrics_GLCM[j];
        j++;
    }

    //Desalocações

    for (i = 0;i < gray_Levels;i++){
        free(MCO_Degree_0[i]);
        free(MCO_Degree_45[i]);
        free(MCO_Degree_90[i]);
        free(MCO_Degree_135[i]);
        free(MCO_Degree_180[i]);
        free(MCO_Degree_225[i]);
        free(MCO_Degree_270[i]);
        free(MCO_Degree_315[i]);
    }

    free(MCO_Degree_0);
    free(MCO_Degree_45);
    free(MCO_Degree_90);
    free(MCO_Degree_135);
    free(MCO_Degree_180);
    free(MCO_Degree_225);
    free(MCO_Degree_270);
    free(MCO_Degree_315);

}
