/*Author: Gustavo Nogueira
 *Date: 28/12/2017
 */

/*This function is responsible for generating each ILBP code.
 *It receives an array containing the central pixel and the other pixels to form the neighborhood of eight.
 *Returns the lowest ILBP code generated by combining binaries generated by the ILBP algorithm. */

int Calculate_ILBP(int *matNeighb){
    double avg,sum = 0;
    int i,j;
    int mat_bin[3][3];
    int vet_bin[9];
    int codF_ILBP;

    //Limiarização Global.
    for (i = 0;i < 3;i++){
        for (j = 0;j < 3;j++){
            sum += *(matNeighb+i*3+j);
        }
    }
    avg = sum / 9.0;

    for (i = 0;i < 3;i++){
        for (j = 0;j < 3;j++){
            if (*(matNeighb+i*3+j) >= avg){
                mat_bin[i][j] = 1;
            }
            else {
                mat_bin[i][j] = 0;
            }
        }
    }
    vet_bin[8] = mat_bin[0][0];
    vet_bin[7] = mat_bin[0][1];
    vet_bin[6] = mat_bin[0][2];
    vet_bin[5] = mat_bin[1][2];
    vet_bin[4] = mat_bin[2][2];
    vet_bin[3] = mat_bin[2][1];
    vet_bin[2] = mat_bin[2][0];
    vet_bin[1] = mat_bin[1][0];
    vet_bin[0] = mat_bin[1][1];

    codF_ILBP = Lower_ILBP(&vet_bin[0]);

    return (codF_ILBP);

}
